prometheus:
  enabled: true
  prometheusSpec:
    storageSpec: {}
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus  # Replace with your desired domain
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    # Optional: Add TLS
    # tls:
    #   - secretName: prometheus-tls
    #     hosts:
    #       - prometheus.yourdomain.com
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx  # Matches the NGINX Ingress controller
    hosts:
      - grafana  # Replace with your desired domain
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    # Optional: Add TLS if you have a certificate
    # tls:
    #   - secretName: grafana-tls
    #     hosts:
    #       - grafana.yourdomain.com